### ISSUE TITLE
Volunteer mengakses website

### ISSUE THREAD

**Issue by alfathya** [FTP-YCAB-Fullstack/D-Last#20]
- [ ] user yang sudah diapprove menjadi volunteer setelah mendaftar volunteer akan login dengan status volunteer
- [ ] volunteer bisa mengakses semua page
- [ ] volunteer bisa mengaskes stories #13 
- [ ] volunteer bisa mengaskes kondisi kesehatan #16 
- [ ] volunteer bisa mengakses volunteer page
- [ ] volunteer bisa mengakses rumah sakit #15 
- [ ] volunteer bisa mengakses service #18
